name: ns
channels:
  - nvidia
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda-cccl=11.8.89=0
  - cuda-cccl_linux-64=12.5.39=0
  - cuda-command-line-tools=12.5.1=0
  - cuda-compiler=12.5.1=0
  - cuda-crt-dev_linux-64=12.5.82=0
  - cuda-crt-tools=12.5.82=0
  - cuda-cudart=12.5.82=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cudart-dev_linux-64=12.5.82=0
  - cuda-cudart-static_linux-64=12.5.82=0
  - cuda-cudart_linux-64=12.5.82=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=12.5.82=0
  - cuda-cupti-dev=12.5.82=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-driver-dev_linux-64=12.5.82=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=12.5.1=0
  - cuda-libraries-dev=12.5.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=12.5.82=0
  - cuda-nvcc-dev_linux-64=12.5.82=0
  - cuda-nvcc-impl=12.5.82=0
  - cuda-nvcc-tools=12.5.82=0
  - cuda-nvcc_linux-64=12.5.82=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvm-dev_linux-64=12.5.82=0
  - cuda-nvvm-impl=12.5.82=0
  - cuda-nvvm-tools=12.5.82=0
  - cuda-nvvp=11.8.87=0
  - cuda-opencl=12.5.39=0
  - cuda-opencl-dev=12.5.39=0
  - cuda-profiler-api=11.8.86=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=12.5.1=0
  - cuda-tools=12.5.1=0
  - cuda-version=12.5=3
  - cuda-visual-tools=12.5.1=0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gds-tools=1.4.0.31=0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.38=h1181459_1
  - libcnpy=0.0.20210729=h780b84a_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvfatbin=12.5.82=0
  - libnvfatbin-dev=12.5.82=0
  - libnvjitlink=12.5.82=0
  - libnvjitlink-dev=12.5.82=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - ninja-base=1.10.2=hd09550d_5
  - nsight-compute=2022.3.0.22=0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pyyaml=6.0.2=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - anyio==4.4.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - av==12.3.0
      - awscli==1.34.5
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bidict==0.23.1
      - bleach==6.1.0
      - blinker==1.8.2
      - botocore==1.35.5
      - cachetools==5.5.0
      - certifi==2024.7.4
      - cffi==1.17.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - colorlog==6.8.2
      - comet-ml==3.44.4
      - comm==0.2.2
      - configargparse==1.7
      - configobj==5.0.8
      - contourpy==1.1.1
      - cryptography==43.0.0
      - cycler==0.12.1
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dearpygui==2.0.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - docutils==0.16
      - dulwich==0.22.1
      - embreex==2.17.7.post5
      - eval-type-backport==0.2.0
      - everett==3.1.0
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastcore==1.7.20
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fire==0.6.0
      - flask==3.0.3
      - fonttools==4.53.1
      - fpsample==0.3.2
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.66.0
      - gsplat==1.0.0
      - gtracer==0.1.0
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - hydra-core==1.3.2
      - idna==3.8
      - imageio==2.35.1
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.4
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.2.19
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.6
      - lovely-numpy==0.2.13
      - lovely-tensors==0.1.18
      - lxml==5.3.0
      - manifold3d==2.5.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - msgpack-numpy==0.4.8
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfbaselines==1.2.8
      - nerfstudio==1.1.3
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - nuscenes-devkit==1.1.9
      - oauthlib==3.2.2
      - open3d==0.18.0
      - opencv-python==4.8.0.76
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.2
      - plotly==5.23.0
      - plyfile==1.0.3
      - pox==0.3.4
      - ppft==1.7.6.8
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.7
      - pycollada==0.8
      - pycparser==2.22
      - pygments==2.18.0
      - pyliblzfse==0.4.1
      - pymeshlab==2023.12.post1
      - pyngrok==7.2.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.9.1
      - python-json-logger==2.0.7
      - python-socketio==5.11.3
      - pytorch-msssim==1.0.0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyzmq==26.2.0
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rawpy==0.21.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.8.0
      - rpds-py==0.20.0
      - rsa==4.7.2
      - rtree==1.3.0
      - s3transfer==0.10.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - shapely==2.0.6
      - shtab==1.7.1
      - simple-knn==0.0.0
      - simple-websocket==1.0.0
      - simplejson==3.19.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - splines==0.3.1
      - stack-data==0.6.3
      - svg-path==6.3
      - sympy==1.13.2
      - tenacity==9.0.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.6.7
      - tinycss2==1.3.0
      - tinycudann==1.7
      - tomli==2.0.1
      - torch==2.1.2+cu118
      - torch-fidelity==0.3.0
      - torchmetrics==1.4.1
      - torchvision==0.16.2+cu118
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - trimesh==4.4.7
      - triton==2.1.0
      - typeguard==4.3.0
      - types-python-dateutil==2.9.0.20240821
      - typing-extensions==4.12.2
      - tyro==0.8.8
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.26.19
      - viser==0.1.27
      - wandb==0.17.7
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==13.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xatlas==0.0.9
      - xxhash==3.5.0
      - yourdfpy==0.0.56
      - zipp==3.20.1
prefix: /home/matbi/miniconda3/envs/ns
