n_iterations: 30000

densification:
  densification_interval: 100
  prune_interval: 100 
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_clone_grad_threshold: 0.0002
  densify_split_grad_threshold: 0.0002
  densify_min_opacity: 0.005
  percent_dense: 0.01 

loss:
  lambda_dssim: 0.2

optimizer:
  type: adam
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.025 
  scaling_lr: 0.005
  rotation_lr: 0.001

max_sh_degree: 3
