defaults:
  - parameters: 3dgrt
  - _self_
  - mode: view
  - experiment: lego

method_name: gsrt
use_wandb: false
evaluate: false
train: false
use_viewer: true

gradcheck: false

white_bg: false
use_batched_rays: false
batch_size: 4096

results_dir: chpt
checkpoint: null
resume_training: true
start_iter: 1
save_results: false
save_interval: 1000
save_start_iter: 1000
checkpoint_type: gsrt

tracer_type: optix 

datasets:
  blender: external://blender 
  mipnerf: external://mipnerf360
  zipnerf: /home/matbi/proj/Fisheye-GS/data/zipnerf-undistorted
  zipnerf_fisheye: /home/matbi/proj/Fisheye-GS/data/zipnerf-fisheye

data_path: ${datasets[${dataset}]}/${scene}

